# Generated by Django 4.2.7 on 2025-05-17 08:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('employees', '0002_remove_salaryhistory_employee_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Contract',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('contract_number', models.CharField(max_length=50, unique=True, verbose_name='Số hợp đồng')),
                ('contract_type', models.CharField(choices=[('probation', 'Thử việc'), ('definite', 'Xác định thời hạn'), ('indefinite', 'Không xác định thời hạn'), ('seasonal', 'Thời vụ'), ('project', 'Theo dự án')], max_length=20, verbose_name='Loại hợp đồng')),
                ('start_date', models.DateField(verbose_name='Ngày bắt đầu')),
                ('end_date', models.DateField(blank=True, null=True, verbose_name='Ngày kết thúc')),
                ('basic_salary', models.DecimalField(decimal_places=0, max_digits=12, verbose_name='Lương cơ bản')),
                ('allowance', models.DecimalField(decimal_places=0, default=0, max_digits=12, verbose_name='Phụ cấp')),
                ('insurance_salary', models.DecimalField(decimal_places=0, default=0, max_digits=12, verbose_name='Lương đóng bảo hiểm')),
                ('status', models.CharField(choices=[('active', 'Đang hiệu lực'), ('expired', 'Đã hết hạn'), ('terminated', 'Đã chấm dứt'), ('pending', 'Chờ ký kết')], default='active', max_length=20, verbose_name='Trạng thái')),
                ('signed_date', models.DateField(verbose_name='Ngày ký')),
                ('notes', models.TextField(blank=True, null=True, verbose_name='Ghi chú')),
                ('file', models.FileField(blank=True, null=True, upload_to='contracts/', verbose_name='File hợp đồng')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='contracts', to='employees.employee', verbose_name='Nhân viên')),
                ('position', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='employees.position', verbose_name='Vị trí công việc')),
            ],
            options={
                'verbose_name': 'Hợp đồng',
                'verbose_name_plural': 'Hợp đồng',
                'ordering': ['-start_date'],
            },
        ),
    ]
