# Generated by Django 4.2.21 on 2025-05-20 03:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employees', '0002_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='position',
            name='code',
            field=models.CharField(max_length=20, unique=True),
        ),
    ]
