# Generated by Django 4.2.8 on 2025-05-20 07:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employees', '0003_alter_position_code'),
    ]

    operations = [
        migrations.AddField(
            model_name='employee',
            name='faculty',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Khoa'),
        ),
        migrations.AddField(
            model_name='employee',
            name='graduation_place',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='Nơi đào tạo'),
        ),
        migrations.AddField(
            model_name='employee',
            name='graduation_year',
            field=models.IntegerField(blank=True, null=True, verbose_name='Năm tốt nghiệp'),
        ),
        migrations.AddField(
            model_name='employee',
            name='ranking',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Xếp loại'),
        ),
        migrations.AlterField(
            model_name='employee',
            name='education_level',
            field=models.CharField(blank=True, choices=[('high_school', 'Trung học phổ thông'), ('college', 'Cao đẳng'), ('university', 'Đại học'), ('master', 'Thạc sĩ'), ('phd', 'Tiến sĩ')], max_length=20, null=True, verbose_name='Trình độ đào tạo'),
        ),
    ]
